bridge-api/.gitignore, bridge-api/src/main/resources/static/index.html, bridge-api/src/test/java/ccc/bridgeapi/document/utils/ControllerTest.java, bridge-api/src/test/java/ccc/bridgeapi/document/utils/RestDocsConfig.java, bridge-api/src/test/java/ccc/bridgeapi/document/utils/RestDocsTestSupport.java, build.gradle
=> [Doc] API Document 자동화

keewe-api/src/main/java/ccc/keeweapi/api/user/ProfileController.java, keewe-api/src/main/java/ccc/keeweapi/config/security/jwt/JwtAuthenticationEntryPoint.java, keewe-api/src/main/java/ccc/keeweapi/config/security/jwt/JwtAuthenticationFilter.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/ActivitiesSearchResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/IncompleteProfileResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/LinkCreateRequest.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/LinkCreateResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/NicknameCreateRequest.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/NicknameCreateResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/UserSignUpResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileService.java, keewe-api/src/main/java/ccc/keeweapi/service/user/UserApiService.java, keewe-api/src/main/java/ccc/keeweapi/utils/SecurityUtil.java, keewe-api/src/test/java/ccc/keeweapi/api/user/ProfileDocumentationTest.java, keewe-api/src/test/java/ccc/keeweapi/api/user/UserSignupControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/service/user/ProfileServiceTest.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java, keewe-domain/src/main/java/ccc/keewedomain/repository/user/ProfileRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/ProfileDomainService.java
=> [Feat] 온보딩 미수행 프로필 조회 / 코드정리

keewe-api/src/main/java/ccc/keeweapi/api/challenge/ChallengeController.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ChallengeCreateRequest.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ChallengeCreateResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ChallengeParticipateRequest.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/main/java/ccc/keeweapi/validator/GraphemeLengthValidator.java, keewe-api/src/main/java/ccc/keeweapi/validator/annotations/GraphemeLength.java, keewe-api/src/test/java/ccc/keeweapi/api/challenge/ChallengeControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/challenge/ChallengeControllerTest.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweRegexs.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java, keewe-domain/src/main/java/ccc/keewedomain/domain/challenge/Challenge.java, keewe-domain/src/main/java/ccc/keewedomain/domain/challenge/ChallengeParticipation.java, keewe-domain/src/main/java/ccc/keewedomain/domain/common/Interest.java, keewe-domain/src/main/java/ccc/keewedomain/domain/common/enums/DefaultInterest.java, keewe-domain/src/main/java/ccc/keewedomain/dto/challenge/ChallengeCreateDto.java, keewe-domain/src/main/java/ccc/keewedomain/dto/challenge/ChallengeParticipateDto.java, keewe-domain/src/main/java/ccc/keewedomain/repository/challenge/ChallengeParticipationRepository.java, keewe-domain/src/main/java/ccc/keewedomain/repository/challenge/ChallengeRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/ChallengeDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/user/UserDomainService.java, keewe-domain/src/main/resources/schema.sql
- 챌린지 등록 API
- 등록 시, 등록자는 해당 챌린지에 참가
- 챌린지 등록 API 테스트
=> [Feat] 챌린지 등록 API

keewe-domain/src/main/java/ccc/keewedomain/domain/challenge/ChallengeParticipation.java, keewe-domain/src/main/java/ccc/keewedomain/domain/challenge/enums/ChallengeParticipationStatus.java, keewe-domain/src/main/java/ccc/keewedomain/repository/challenge/ChallengeParticipationRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/ChallengeDomainService.java, keewe-domain/src/main/resources/schema.sql
#81 
- 챌린지 참가 상태 필드 추가
- ChallengeParticipation 생성 시 초기 status 설정
- 참가 여부 조회 쿼리 상태 활용하도록 수정
- ChallengeParticipation chllenger_id, status 인덱스 추가
=> [Feat] 챌린지 참가 상태 추가

keewe-domain/src/main/java/ccc/keewedomain/domain/challenge/ChallengeParticipation.java, keewe-infra/src/main/java/ccc/keeweinfra/service/NaverInfraService.java
=> [Feat] 챌린지 참가 일주일 기준 변경

build.gradle, keewe-api/src/test/java/ccc/keeweapi/service/user/ProfileServiceTest.java, keewe-domain/src/main/java/ccc/keewedomain/domain/user/Profile.java, keewe-domain/src/test/java/ccc/keewedomain/domain/user/ProfileDomainServiceTest.java, keewe-domain/src/test/java/ccc/keewedomain/domain/user/ProfileTest.java
=> [Chore] QueryDsl 세팅

keewe-api/src/main/java/ccc/keeweapi/api/challenge/ChallengeController.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ChallengeParticipationResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/test/java/ccc/keeweapi/api/challenge/ChallengeControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/domain/challenge/ChallengeParticipation.java, keewe-domain/src/main/java/ccc/keewedomain/repository/challenge/ChallengeParticipationRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/ChallengeDomainService.java
=> [Feat] 챌린지 참여 Api

keewe-api/src/main/java/ccc/keeweapi/api/KeeweControllerAdvice.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java
- #91 
- MethodArgumentNotValidException KeeweException으로 처리
- ERR400 유효성 검사 실패로 수정
=> [Fix] Bean Validation 예외 처리

keewe-api/src/main/java/ccc/keeweapi/api/KeeweControllerAdvice.java, keewe-api/src/main/java/ccc/keeweapi/api/user/ProfileController.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/OnboardRequest.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/OnboardResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/ProfileAssembler.java, keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java, keewe-api/src/main/java/ccc/keeweapi/validator/GraphemeLengthValidator.java, keewe-api/src/main/java/ccc/keeweapi/validator/PostContentLengthValidator.java, keewe-api/src/test/java/ccc/keeweapi/api/user/ProfileControllerTest.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java, keewe-core/src/main/java/ccc/keewecore/utils/KeeweStringUtil.java, keewe-domain/src/main/java/ccc/keewedomain/domain/user/User.java, keewe-domain/src/main/java/ccc/keewedomain/dto/user/OnboardDto.java, keewe-domain/src/main/java/ccc/keewedomain/service/user/ProfileDomainService.java, keewe-domain/src/main/resources/schema.sql
#88 
- 온보딩 등록 API
- 온보딩 등록 API 문서화용 테스트
=> [Feat] 온보딩 등록 API 

keewe-api/src/main/java/ccc/keeweapi/api/insight/DrawerController.java, keewe-api/src/main/java/ccc/keeweapi/component/InsightAssembler.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/DrawerResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/DrawerApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/InsightApiService.java, keewe-api/src/test/java/ccc/keeweapi/api/insight/DrawerControllerTest.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/insight/Drawer.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/DrawerRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/DrawerDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java
- 나의 서랍 목록 조회 API
- close #122
=> [Feat] 나의 서랍 목록 조회 API

keewe-api/src/main/java/ccc/keeweapi/api/user/ProfileController.java, keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/FollowToggleResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java, keewe-api/src/test/java/ccc/keeweapi/api/user/ProfileControllerTest.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweConsts.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java, keewe-domain/src/main/java/ccc/keewedomain/dto/user/FollowToggleDto.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/Follow.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/id/FollowId.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/FollowRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/UserRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/user/ProfileDomainService.java
=> [Feat] 유저 팔로잉 API

keewe-api/src/main/java/ccc/keeweapi/api/challenge/ChallengeController.java, keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/InsightProgressResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ParticipationProgressResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/test/java/ccc/keeweapi/api/challenge/ChallengeControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/challenge/ChallengeParticipation.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeParticipationQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeParticipationQueryRepositoryImpl.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/ChallengeDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java
- 인사이트 등록 화면 챌린지 참가 현황 조회
- close #135
=> [Feat] 인사이트 등록 화면 챌린지 참가 현황 조회

keewe-api/src/main/java/ccc/keeweapi/api/insight/InsightController.java, keewe-api/src/main/java/ccc/keeweapi/component/InsightAssembler.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/ChallengeRecordResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/InsightApiService.java, keewe-api/src/test/java/ccc/keeweapi/api/insight/InsightControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java, keewe-domain/src/test/java/ccc/keewedomain/service/insight/InsightDomainServiceTest.java
- 인사이트 챌린지 참가 정보 API 및 테스트
- close #143
=> [Feat] 인사이트 조회 화면 인사이트의 챌린지 참가 정보 API

keewe-api/src/main/java/ccc/keeweapi/api/user/UserController.java, keewe-api/src/main/java/ccc/keeweapi/component/InsightAssembler.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/InsightGetResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/InsightApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/user/UserApiService.java, keewe-api/src/test/java/ccc/keeweapi/api/insight/InsightControllerTest.java, keewe-core/src/main/java/ccc/keewecore/aop/ApiBlockingAspect.java, keewe-core/src/main/java/ccc/keewecore/aop/annotations/LocalOnlyAllowedApi.java, keewe-core/src/main/java/ccc/keewecore/aop/annotations/LocalOnlyApi.java, keewe-domain/src/main/java/ccc/keewedomain/dto/insight/InsightDetailDto.java, keewe-domain/src/main/java/ccc/keewedomain/dto/insight/InsightGetDto.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java
홈 화면 작업이 아직 반영이 안돼있어서 인사이트 상세부터 작업하였습니다.
추가로, 회원 가입이 너무 불편해서 로컬 전용 API를 만들었어요.
=> [Feat] 인사이트 게시물 응답 시 북마크 여부 추가 (인사이트 상세)

keewe-api/src/test/java/ccc/keeweapi/controller/api/user/ProfileControllerTest.java
- description, summary 수정
- close #183
=> [Fix] 마이페이지 유저 정보 조회 문서화용 테스트 수정

keewe-api/src/main/java/ccc/keeweapi/component/UserAssembler.java, keewe-api/src/main/java/ccc/keeweapi/config/security/jwt/JwtUtils.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/UserSignUpResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/user/UserApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserSignupControllerTest.java
토큰 유효시간
- 약 4일 => 41일로 조정
회원 가입 시 기존 가입 유저 식별 응답 추가.
=> [Chore] 토큰 시간 조정, 로그인 시 가입 여부 응답 추가

keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/user/ProfileController.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/BlockUserResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/MyBlockUserListResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/MyBlockUserResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/UnblockUserResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/user/ProfileControllerTest.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/title/TitleAchievement.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/title/id/TitleAchievementId.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/Block.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/id/BlockId.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/BlockQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/BlockRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/TitleAchievementRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/user/ProfileDomainService.java, keewe-domain/src/main/resources/ddl/ddl.sql, keewe-domain/src/main/resources/dml/issue-189_dml.sql
1. 차단 도메인 정의
2. 사용자 차단 API, 문서화 테스트
3. 사용자 차단 해제 API, 문서화 테스트
4. 나의 차단 목록 조회 API, 문서화 테스트
5. TitleAchievementId 위치 수정
- close #189
=> [Feat] 차단 도메인 정의, 차단, 차단 해제, 차단 목록 조회 API

keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/user/ProfileController.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/AllAchievedTitleResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/user/ProfileControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/User.java
=> [Feat] 전체 획득 타이틀 조회 대표 타이틀 id 추가

keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeController.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/MyChallengeResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ParticipatingChallengeResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeParticipationQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/ChallengeDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java, keewe-domain/src/main/resources/ddl/ddl.sql
1. 챌린지 홈 나의 참가중인 챌린지 조회 API
- close #199
=> [Feat] 챌린지 홈 나의 참가중인 챌린지 조회 API

keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeController.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ChallengeDetailResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java
- 챌린지 상세 조회 기록 API
- close #207
=> [Feat] 챌린지 상세 조회 API

keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java
=> [Fix] 챌린지 홈 종료된 챌린지 조회 Response 순서 수정

keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightBookmarkController.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightCommentController.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightController.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightDrawerController.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightReactionController.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightCommandApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightCommentCommandApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightDrawerCommandApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightReactionCommandApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightCommentQueryApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightDrawerQueryApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightBookmarkControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightCommentControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightDrawerControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightReactionControllerTest.java
Insight 서비스 Command Query 분리 적용
=> [NO-ISSUE] Insight api service CQ 분리

keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java, keewe-core/src/main/java/ccc/keewecore/consts/LockType.java, keewe-core/src/main/java/ccc/keewecore/utils/RedisLockUtils.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/ChallengeDomainService.java
- close #223
- 챌린지 참여 시 참여하고 있는 챌린지가 있는 지 여부를 체크하는 과정에서 발생할 수 있는 동시성 문제를 해결해요.
=> [Fix] 챌린지 참여 동시성 버그 수정

keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeController.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/OpenedChallengeResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/query/ChallengeQueryApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/command/ChallengeCommandDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/query/ChallengeParticipateQueryDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/query/ChallengeQueryDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java
- close #201 
- 진행중인 챌린지 페이지네이션 조회 API 개발
- 챌린지에 대한 Command Query 분리
=> [Feat] 진행중인 챌린지 페이지네이션 조회 기능

keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightBookmarkControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightCommentControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightDrawerControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightReactionControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserBlockControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserProfileControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserRelationControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserSignupControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserTitleControllerTest.java
- API 문서 태그 목적에 맞게 분리.
- PR test 체크
=> [Chore] API 문서 태그 분리

keewe-core/src/main/java/ccc/keewecore/utils/RedisLockUtils.java
=> [Fix] RedisLock Value Type 수정

keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeController.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationController.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/CompletedChallengeResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/query/ChallengeParticipationQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeParticipationQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/query/ChallengeParticipateQueryDomainService.java
- close #236
- 완료된 챌린지를 페이지네이션 조회하는 기능 추가
- [종료된 챌린지 전체 목록](https://www.figma.com/file/myrpWyrITG5YM9o9I5Ems7/%ED%82%A4%EC%9C%84-Keewe?node-id=7654%3A34807&t=mKLzC5YdFTtTvHaM-0)
=> [Feat] 완료된 챌린지 페이지네이션 조회

keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/OpenedChallengeResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/query/ChallengeQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeControllerTest.java
=> [NO-ISSUE] 챌린지 페이지네이션 시 응답 필드 변경

keewe-api/src/main/java/ccc/keeweapi/component/CommentAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightCommentController.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/InsightCommentCountResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/PreviewCommentResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/RepresentativeCommentResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/RepresentativeCommentsResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightCommentQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightCommentControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/CommentQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/CommentDomainService.java
- close #241 
인사이트 대표 댓글 조회 요구사항 반영
- 대표 댓글 조회 API 변경
- 인사이트 댓글 개수 조회 API 분리
- 댓글 조회 쿼리 개선
- [대표 댓글 변경 사항](https://www.figma.com/file/myrpWyrITG5YM9o9I5Ems7/%ED%82%A4%EC%9C%84-Keewe?node-id=8207%3A38689&t=KMoi7B4FRh32WKv6-4)
=> [Feat] 인사이트 대표 댓글 조회 API 변경사항 반영 및 리팩토링

keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
=> [Fix] Circular dependency remove

keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightCommentQueryApiService.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/CommentQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/CommentDomainService.java
=> [Fix] 인사이트 id 제약 조건 추가

keewe-batch/src/main/java/ccc/keewebatch/batch/ChallengeRecordCheckConfiguration.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/challenge/ChallengeParticipation.java
- close #252  
- 챌린지 참가 cancel, expire 시 endDate 변경
> batch, api 둘 다 배포해야 함
=> [Feat] 챌린지 참가 조기 종료 시 endDate 변경

keewe-api/src/main/java/ccc/keeweapi/component/ReportAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/report/ReportController.java, keewe-api/src/main/java/ccc/keeweapi/dto/report/CommentReportRequest.java, keewe-api/src/main/java/ccc/keeweapi/dto/report/InsightReportRequest.java, keewe-api/src/main/java/ccc/keeweapi/service/report/ReportApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/report/ReportControllerTest.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweConsts.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java, keewe-domain/src/main/java/ccc/keewedomain/dto/insight/ReportCreateDto.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/insight/enums/ReportTarget.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/insight/enums/ReportType.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/report/Report.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/CommentDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/report/CommentReportDomainServiceImpl.java, keewe-domain/src/main/java/ccc/keewedomain/service/report/InsightReportDomainServiceImpl.java, keewe-domain/src/main/java/ccc/keewedomain/service/report/ReportDomainService.java, keewe-domain/src/main/resources/ddl/ddl.sql
=> [Feat] 댓글 신고 기능 추가

keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightController.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
- 북마크한 인사이트 조회
- [북마크](https://www.figma.com/file/myrpWyrITG5YM9o9I5Ems7/%ED%82%A4%EC%9C%84-Keewe?node-id=1918%3A83999&t=ekkyeTM3fhxcVuO5-1)
=> [Feat] 북마크한 인사이트 조회

keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserProfileController.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/InterestsResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserProfileControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/UserQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/user/ProfileDomainService.java
=> [Feat] 내 관심사 조회 API

keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeController.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationController.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/query/ChallengeParticipateQueryDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/query/ChallengeQueryDomainService.java
=> [NO-ISSUE] 미사용 코드 제거

keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeParticipationQueryRepository.java
=> [Fix] existsByChallengerIdAndStatus 쿼리 경로 수정

keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/FollowRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/user/ProfileDomainService.java
- 존재하지 않는 followId 삭제 시 예외 발생하는 문제 수정
=> [Fix] follow 존재할 때만 delete

keewe-api/src/main/java/ccc/keeweapi/config/interceptor/LoggingInterceptor.java, keewe-api/src/main/java/ccc/keeweapi/config/security/WebMvcConfig.java, keewe-api/src/main/java/ccc/keeweapi/config/security/jwt/JwtAuthenticationEntryPoint.java, keewe-api/src/main/java/ccc/keeweapi/config/security/jwt/JwtAuthenticationFilter.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/KeeweControllerAdvice.java, keewe-api/src/main/resources/logback-spring.xml, keewe-infra/src/main/java/ccc/keeweinfra/config/AsyncConfig.java
=> [NO-ISSUE] USER_ID Logback 로깅 추가

keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/User.java
- close #276 
- 챌린지 친구 조회 API 자신 제외
=> [Fix] 챌린지 친구 조회 API 자신 제외

keewe-api/src/main/java/ccc/keeweapi/aop/BlockFilterAspect.java, keewe-api/src/main/java/ccc/keeweapi/aop/annotations/BlockFilter.java, keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationController.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightCommentController.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightController.java, keewe-api/src/main/java/ccc/keeweapi/dto/BlockFilteringResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/FriendResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/CommentResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/InsightGetForHomeResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/PreviewCommentResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/ReplyResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationControllerTest.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/BlockQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/user/ProfileDomainService.java
- close #279
- 응답에서 차단한 유저 관련 내용 삭제 AOP 추가
- 차단 기능 적용
- [차단 요구사항](https://www.figma.com/file/myrpWyrITG5YM9o9I5Ems7/%ED%82%A4%EC%9C%84-Keewe?node-id=2150-41763&t=DGIRZRPTn0XiT9XD-4)
=> [Feat] 차단 관련 API 응답 필터링

keewe-domain/src/main/resources/ddl/ddl.sql, keewe-domain/src/main/resources/dml/issue-278_dml.sql
- close #278 
- DDL `insight.contents` 400자로 수정
- 수정용 쿼리 작성
=> [Fix] 인사이트 최대 글자 수 400자로 수정

keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java, keewe-api/src/main/resources/logback-spring.xml, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
- 병렬 스트림에서 DB Session을 사용하지 않도록 변경해요
=> [Fix] 병렬 스트림에서 DB Session을 사용하지 않도록 변경해요

keewe-api/src/main/java/ccc/keeweapi/service/notification/query/NotificationQueryApiService.java
=> [Fix] Add tx to notification paginate

keewe-api/src/main/java/ccc/keeweapi/component/InsightAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightController.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/InsightStatisticsResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightControllerTest.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/BookmarkQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/BookmarkQueryDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
- close #290 
- 인사이트 통계 조회 API를 개발해요
빨간 박스 부분이에요
=> [Feat] 인사이트 통계 조회 API

keewe-api/src/main/java/ccc/keeweapi/controller/api/KeeweControllerAdvice.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java, keewe-api/src/main/java/ccc/keeweapi/utils/BlockFilterUtil.java
- close #301
- 나의 챌린지 인사이트 조회 차단 필터링 제거
- 999 응답 시 상태 코드 500으로 설정
=> [Fix] 나의 챌린지 인사이트 조회 차단 필터링 제거, 999 응답 HTTP 상태 코드 500 설정

keewe-api/src/main/java/ccc/keeweapi/dto/notification/NotificationResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/CommentNotificationProcessor.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/CommentReplyNotificationProcessor.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/FollowNotificationProcessor.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/ReactionNotificationProcessor.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/TitleNotificationProcessor.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/notification/NotificationControllerTest.java
=> [Fix] 알림 응답 시 시간 정보 추가

keewe-api/src/main/java/ccc/keeweapi/component/NotificationAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/notification/NotificationController.java, keewe-api/src/main/java/ccc/keeweapi/dto/notification/UnreadNotificationExistenceResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/query/NotificationQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/notification/NotificationControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/notification/NotificationQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/notification/query/NotificationQueryDomainService.java
- close #305 
- 확인하지 않은 알림 존재를 확인하는 기능을 개발했어요.
따로 시안이 없는거같은데, 알림 아이콘에 빨간 뱃지가 붙을 예정이에요
=> [Feat] 미확인 알림 존재 여부 체크 기능 개발

keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightController.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
- 
- 북마크 조회 순서를 북마크 설정 순서대로 정렬하도록 조정했습니다!
- 
- [간략한제목](링크)
=> [Feat] 북마크 조회 시 북마크 설정 순서대로

keewe-api/src/main/java/ccc/keeweapi/component/InsightAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightController.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/InsightGetForBookmarkedResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/dto/insight/InsightGetForBookmarkedDto.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
- hotfix
- 북마크한 시간을 반환하지 않아 문제 발생
- 해결
=> [HOTFIX] 북마크 인사이트 조회 시, 북마크한 시간 함께 반환

keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserSignUpController.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/user/UserApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserSignupControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/User.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/FollowRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/UserQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/command/ChallengeCommandDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/title/AbstractTitleAcquireProcessor.java, keewe-domain/src/main/java/ccc/keewedomain/service/title/InsightTitleAcquireProcessor.java, keewe-domain/src/main/java/ccc/keewedomain/service/title/SignUpTitleAcquireProcessor.java, keewe-domain/src/main/java/ccc/keewedomain/service/user/command/ProfileCommandDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/user/command/UserCommandDomainService.java, keewe-infra/src/main/java/ccc/keeweinfra/service/image/S3StoreService.java
- close #310
1. 유저 상태 변경 - 86d653735dda9701a820343f3f71b0baf49103ae
2. 참여중인 챌린지 OUT 처리
3. 팔로워/팔로잉 제거 - eac966dcb3ff54220a2597b6795e16a424f3cd86
4. 마이페이지 조회 가능하도록 처리 (남아있는 인사이트가 있어서 이렇게 처리함) - 5c0536f239dcf8b54ddb38c65e6f48fa0e911a6b
- #### aggregate - 86c20a7d6912e67f0672441fb393c69e1b3aa40d
=> [Feat] 유저 탈퇴 기능 개발

keewe-api/src/main/java/ccc/keeweapi/dto/insight/request/CommentCreateRequest.java, keewe-domain/src/main/resources/ddl/ddl.sql
=> [Hotfix] 댓글 길이 2000자로 수정

keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightReactionCommandApiService.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweConsts.java, keewe-domain/src/main/java/ccc/keewedomain/cache/domain/insight/CFirstReaction.java, keewe-domain/src/main/java/ccc/keewedomain/cache/repository/insight/CFirstReactionAggregationRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/title/enums/ReactionTitle.java, keewe-domain/src/main/java/ccc/keewedomain/service/title/FirstReactionTitleAcquireProcessor.java
#341
- 첫 리엑션 타이틀 추가 기능 구현
- 리엑션 관련 이슈 3개 각자 머지 후 배포 (각 타이틀 기준이 하나로 묶기 애매한거 같습니당)
=> [Feat] 첫 리엑션 타이틀 추가

keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java
=> [Fix] 챌린지 인사이트 기록 횟수 버그 수정

keewe-batch/src/main/java/ccc/keewebatch/batch/DailyChallengeRecorder.java, keewe-core/src/main/java/ccc/keewecore/utils/DateTimeUtils.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeRecordRepository.java
=> [Refactor] 챌린지 기록/성공/실패 처리 배치 리팩터링

keewe-core/src/main/java/ccc/keewecore/consts/KeeweConsts.java, keewe-domain/src/main/java/ccc/keewedomain/cache/domain/insight/CReactionCountForTitle.java, keewe-domain/src/main/java/ccc/keewedomain/cache/repository/insight/CFirstReactionAggregationRepository.java, keewe-domain/src/main/java/ccc/keewedomain/cache/repository/insight/CReactionCountTitleRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/title/enums/ReactionTitle.java, keewe-domain/src/main/java/ccc/keewedomain/service/title/ReactionCountTitleAcquireProcessor.java
=> [Feat] 아낌없이 주는 나무 타이틀 구현

keewe-api/src/main/java/ccc/keeweapi/controller/api/search/SearchController.java, keewe-api/src/main/java/ccc/keeweapi/service/search/query/SearchQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/search/SearchControllerTest.java, keewe-core/src/main/java/ccc/keewecore/consts/SearchType.java, keewe-domain/src/main/java/ccc/keewedomain/dto/SearchDto.java, keewe-domain/src/main/java/ccc/keewedomain/dto/challenge/ChallengeSearchDto.java, keewe-domain/src/main/java/ccc/keewedomain/dto/insight/InsightGetForSearch.java, keewe-domain/src/main/java/ccc/keewedomain/dto/user/UserSearchDto.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/UserQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/search/ChallengeSearcher.java, keewe-domain/src/main/java/ccc/keewedomain/service/search/InsightSearcher.java, keewe-domain/src/main/java/ccc/keewedomain/service/search/Searcher.java, keewe-domain/src/main/java/ccc/keewedomain/service/search/UserSearcher.java, keewe-domain/src/main/java/ccc/keewedomain/service/search/query/SearchQueryDomainService.java
- #348 
- 인사이트, 유저, 첼린지 검색 기능 개발
- 일단 배포~ 테스트 및 doc 테스트 추가 필요
- [검색 관련 피그마](https://www.figma.com/file/myrpWyrITG5YM9o9I5Ems7/%ED%82%A4%EC%9C%84-Keewe?type=design&node-id=10366-44805&mode=design&t=8QXsyVgkRlFYUxPu-4)
=> [Feat] 검색기능 개발

.gitignore, keewe-api/src/main/resources/logback-spring.xml
=> [Chore] 로그 컬러 출력 적용

build.gradle, keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightController.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiServiceKt.kt, keewe-api/src/main/java/ccc/keeweapi/service/notification/query/NotificationQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/dto/insight/InsightGetForHomeDto.java, keewe-domain/src/main/java/ccc/keewedomain/dto/insight/InsightWriterDto.java, keewe-domain/src/main/java/ccc/keewedomain/dto/insight/ReactionAggregationGetDto.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/common/BaseTimeEntity.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/insight/Insight.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/insight/Reaction.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/User.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/ReactionAggregationRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/ReactionDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/search/query/SearchQueryDomainService.java, keewe-domain/src/main/kotlin/ccc/keewedomain/insight/ListHomeInsightsQueryService.kt, keewe-domain/src/test/java/ccc/keewedomain/service/insight/ReactionDomainServiceTest.java, keewe-infra/src/main/java/ccc/keeweinfra/config/CoroutineConfig.kt
=> [Refactor] 홈 인사이트 페이지네이션 조회 기능 Kotlin/Coroutine Migration
