keewe-api/src/main/java/ccc/keeweapi/api/nest/PostController.java, keewe-api/src/main/java/ccc/keeweapi/dto/nest/PostAssembler.java, keewe-api/src/main/java/ccc/keeweapi/dto/nest/QuestionPostCreateRequest.java, keewe-api/src/main/java/ccc/keeweapi/service/nest/PostApiService.java, keewe-api/src/test/java/ccc/keeweapi/api/nest/PostControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/domain/nest/QuestionPost.java, keewe-domain/src/main/java/ccc/keewedomain/dto/nest/QuestionPostDto.java, keewe-domain/src/main/java/ccc/keewedomain/service/nest/PostDomainService.java
#57
- 질문글 생성 API
- 질문글 생성 API 테스트
=> [Feat] 질문글 생성 API

keewe-api/src/test/java/ccc/keeweapi/api/nest/PostControllerTest.java, keewe-api/src/test/java/ccc/keeweapi/api/user/ProfileDocumentationTest.java, keewe-api/src/test/java/ccc/keeweapi/document/utils/ApiDocumentationTest.java
#69 
- 테스트 Authorization 헤더에 실제 JWT를 넣도록 수정
=> [Fix] API 문서화 JWT 인식하도록 수정

keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ChallengeCreateResponse.java, keewe-api/src/test/java/ccc/keeweapi/api/challenge/ChallengeControllerTest.java
#76 
ChallengeCreateResponse에 생성된 Challenge의 Id 추가
=> [Fix] 챌린지 생성 응답에 challengeId 추가

keewe-api/src/main/java/ccc/keeweapi/api/challenge/ChallengeController.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ParticipationCheckResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/test/java/ccc/keeweapi/api/challenge/ChallengeControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/ChallengeDomainService.java
- 챌린지 참여 여부 API입니다
- res 예시 :
"data": {
"participation": false
}
=> [Feat] 챌린지 참여 여부 API #82

keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/challenge/ChallengeParticipation.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/insight/Insight.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeParticipationRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/DrawerRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/ChallengeDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/CommentDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java, keewe-domain/src/main/resources/ddl/ddl.sql, keewe-domain/src/main/resources/dml/issue-126_dml.sql, keewe-domain/src/test/java/ccc/keewedomain/service/insight/CommentDomainServiceTest.java, keewe-domain/src/test/java/ccc/keewedomain/service/insight/InsightDomainServiceTest.java
- 인사이트 작성 시 챌린지 기록 기능 추가
- 인사이트 테이블에 유효한 기록 확인을 위한 valid 컬럼 추가
- 인사이트 생성 domain service 테스트 작성
- 오류 수정
- 서랍 find 실패 시 오류 코드 수정 
- ddl.sql reaction pk 이름 오타 수정
- 인사이트 생성 시 participation 값에 따라 기록하거나 하지 않도록 수정
- close #126
=> [Feat] 인사이트 작성 시 챌린지 기록

keewe-api/src/main/java/ccc/keeweapi/api/insight/DrawerController.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/DrawerApiService.java, keewe-api/src/test/java/ccc/keeweapi/api/insight/DrawerControllerTest.java
=> [Feat] 유저의 서랍 목록 조회

keewe-api/src/main/java/ccc/keeweapi/api/insight/InsightController.java, keewe-api/src/main/java/ccc/keeweapi/component/InsightAssembler.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/InsightMyPageResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/InsightApiService.java, keewe-api/src/test/java/ccc/keeweapi/api/insight/InsightControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/dto/insight/InsightMyPageDto.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/insight/Insight.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java, scripts/batch_deploy.sh
1. 마이 페이지 인사이트 조회
- userId로 cursor paging을 통한 인사이트 조회
- 추가로 drawerId로 폴더 별 인사이트 조회
- 문서화용 테스트
2. batch_deploy 스크립트 수정
- close #157
=> [Feat] 마이페이지 인사이트 조회

keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/Title.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/TitleAchievement.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/enums/TitleCategory.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/id/TitleAchievementId.java, keewe-domain/src/main/resources/ddl/ddl.sql, keewe-domain/src/main/resources/dml/issue-171_dml.sql, keewe-domain/src/main/resources/dml/title_dml.sql
1. Title 엔티티, DDL 작성
2. TitleAchievement 엔티티, DDL 작성
3. 이슈 관련 DML 작성
하고 나서 보니까 Title을 Enum으로 하는 방법도 가능할 것 같네요. 이 경우 장단점은
장점
- Title 테이블을 사용하지 않아도 됨.
- 특정 유저의 타이틀을 모두 조회하는 경우 편리
단점
- 새로운 타이틀을 추가하려면 api 서버 재시작 필요.
- image URL은 어떻게 설정할지 고민 필요.
의견 있으면 말씀해주세요 ㅎㅎ
=> [Feat] 타이틀 도메인 정의

keewe-api/src/main/java/ccc/keeweapi/component/CommentAssembler.java, keewe-api/src/main/java/ccc/keeweapi/component/InsightAssembler.java, keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/user/ProfileController.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/User.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/CommentQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/UserQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java, keewe-domain/src/main/resources/ddl/ddl.sql, keewe-domain/src/main/resources/dml/issue-182_dml.sql
1. 유저 엔티티에 대표 타이틀 추가
2. 대표 타이틀, 프로필 이미지 URL 임시 값 제거
수정 사항
1. 팔로워 목록 조회 컨트롤러 required false를 true로 변경(삭제)
2. 댓글 테이블 부모 댓글 외래키 제약 조건 추가
- close #182
=> [Feat] 유저 대표 타이틀 추가

keewe-batch/src/main/java/ccc/keewebatch/batch/ChallengeRecordCheckConfiguration.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java
1. 남은 일 수 < 남은 인사이트 개수인 경우 실패
2. 마지막 주 조건 달성시 종료일보다 빠르게 성공
- close #204
=> [Feat] 챌린지 기록 검사 배치 - 매일 진행현황 확인하도록 변경

keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationController.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ChallengerCountResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/TogetherChallengerResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeParticipationQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/ChallengeDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java
- close #208 
- 챌린지 상세 함께 기록 참가자 목록 조회 API (최대 5개 조회)
- API 문서화용 테스트 작성
- 챌린지 참가 중인 인원 조회 API
- API 문서화용 테스트 작성
- 마이 페이지 프로필 조회 API 자기 소개 "introduction" 실제 값 들어가도록 수정
- [챌린지 상세 함께 기록](https://www.figma.com/file/myrpWyrITG5YM9o9I5Ems7/%ED%82%A4%EC%9C%84-Keewe?node-id=3800%3A28287&t=3ekfn9Zd2UPy5I9w-4)
=> [Feat] 챌린지 상세 함께 기록 조회 API, 챌린지 참가 중인 인원 조회 API

keewe-domain/src/main/resources/ddl/ddl.sql, keewe-domain/src/main/resources/dml/issue-230_dml.sql
- close #230
- ddl에 FK 설정 추가
- 기존 DB에 추가할 SQL 작성
=> [Fix] DDL FK 추가

keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeController.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ChallengeDetailResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ParticipatingChallengeDetailResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeControllerTest.java
- close #234
- ~~챌린지 상세 조회 API 필드 `challengeCategory`, `createAt` 추가~~
- ~~변경 내용 문서화 테스트 반영~~
- 챌린지 상세 조회 참가 전, 참가 중으로 분리
- 참가 전 챌린지 상세 조회 API 필드 수정(불필요한 필드 제거)
- 참가 중 챌린지 상세 조회 API 추가
- 챌린지 상세 조회 참가 전, 참가 중 문서화용 테스트 추가
- [참여 전 챌린지 상세](https://www.figma.com/file/myrpWyrITG5YM9o9I5Ems7/%ED%82%A4%EC%9C%84-Keewe?node-id=3800%3A28283&t=JuMWhs31m8kOgSSO-4)
- [참여 중 챌린지 상세](https://www.figma.com/file/myrpWyrITG5YM9o9I5Ems7/%ED%82%A4%EC%9C%84-Keewe?node-id=7821%3A37069&t=JuMWhs31m8kOgSSO-4)
=> [Fix] 챌린지 상세 조회 API 참가 전, 참가 중 분리

keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationController.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/MyParticipationProgressResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/challenge/ChallengeParticipation.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
- close #254 
- 챌린지 참가 현황 조회 API todayRecorded, weekCompleted 필드 추가
- [현황별 메시지](https://www.figma.com/file/myrpWyrITG5YM9o9I5Ems7/%ED%82%A4%EC%9C%84-Keewe?node-id=3679-25197&t=DyGYVHLXebJQVbUU-4)
=> [Feat] 인사이트 생성 시 챌린지 참가 현황 조회 API 수정 반영

keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightController.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
- close #256
- 챌린지 상세 전체기록 페이지네이션 조회 API
- writerId로 필터링, 비어있을 시 전체 조회
- [챌린지 상세 인사이트](https://www.figma.com/file/myrpWyrITG5YM9o9I5Ems7/%ED%82%A4%EC%9C%84-Keewe?node-id=3641-23800&t=wYPWb5DnIgTX5wra-4)
=> [Feat] 챌린지 상세 전체기록 페이지네이션 조회 API

keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationController.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ParticipatingChallengeResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ParticipationUpdateRequest.java, keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationControllerTest.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java, keewe-domain/src/main/java/ccc/keewedomain/dto/challenge/ParticipationUpdateDto.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/challenge/ChallengeParticipation.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/command/ChallengeCommandDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/query/ChallengeParticipateQueryDomainService.java
- close #269
- 참가중인 챌린지 조회 API 수정
- 참가 정보 추가
- 참가자 수 필드 제거(참가자 수 조회 API와 기능 중복)
- 챌린지 참가 정보 수정 API 추가
- 이번 주 남은 day보다 더 많은 인사이트를 작성해야 하는 경우 예외
- 오늘보다 이전으로 duration을 설정하는 경우 fail
- [내 목표 수정](https://www.figma.com/file/myrpWyrITG5YM9o9I5Ems7/%ED%82%A4%EC%9C%84-Keewe?node-id=3806-29663&t=Tw9meND78y9MRR5N-4)
=> [Feat] 챌린지 참가 정보 수정 API, 참가중인 챌린지 조회 API 수정

keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightDrawerController.java, keewe-api/src/main/java/ccc/keeweapi/dto/insight/DrawerUpdateRequest.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightDrawerCommandApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightDrawerControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/insight/Drawer.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/insight/Insight.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/DrawerDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
- 폴더 삭제 API
- 폴더 수정 API
- [폴더 편집](https://www.figma.com/file/myrpWyrITG5YM9o9I5Ems7/%ED%82%A4%EC%9C%84-Keewe?node-id=4348-35165&t=GlKl3gP08C6H9jIv-4)
=> [Feat] 폴더 삭제, 수정 API

keewe-api/src/main/java/ccc/keeweapi/controller/api/notification/NotificationController.java, keewe-api/src/main/java/ccc/keeweapi/dto/notification/NotificationResponse.java, keewe-api/src/main/java/ccc/keeweapi/dto/notification/PaginateNotificationResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/CommentNotificationProcessor.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/CommentReplyNotificationProcessor.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/NotificationProcessor.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/ReactionNotificationProcessor.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/TitleNotificationProcessor.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/command/NotificationCommandApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/query/NotificationQueryApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/notification/NotificationControllerTest.java, keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java, keewe-core/src/main/java/ccc/keewecore/utils/ListUtils.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/insight/Reaction.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/notification/Notification.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/notification/enums/NotificationCategory.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/notification/enums/NotificationContents.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/notification/NotificationQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/notification/NotificationRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/ReactionDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/notification/command/NotificationCommandDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/notification/query/NotificationQueryDomainService.java, keewe-domain/src/main/resources/ddl/ddl.sql, keewe-domain/src/main/resources/ddl/issue-#281_ddl.sql
- #282
1. 알림 페이지네이션 
- 댓글,답글,타이틀,반응만 대응 
- 추후 개발 추가 예정
2. 알림 읽음처리
테스트 안해봄 ㅎ
Next TODO: 알림 생성
=> [Feat] 알림 목록 조회 / 알림 읽음 처리 기능 개발

keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightCommandApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightCommentCommandApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightReactionCommandApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightCommentQueryApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightDrawerQueryApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/CommentNotificationProcessor.java, keewe-api/src/main/java/ccc/keeweapi/service/notification/CommentReplyNotificationProcessor.java, keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java, keewe-api/src/main/java/ccc/keeweapi/utils/BlockedResourceManager.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/CommentQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/CommentDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/command/CommentCommandDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/CommentQueryDomainService.java, keewe-domain/src/main/java/ccc/keewedomain/service/report/CommentReportDomainServiceImpl.java, keewe-domain/src/test/java/ccc/keewedomain/service/insight/CommentDomainServiceTest.java
- close #297
- 미리보기에서 차단된 유저의 댓글을 넘기고 다음 순서에 해당하는 댓글을 노출
- 네이밍 수정 `BlockUtil` -> `BlockedResourceManager`, 메서드 이름 포함
=> [Fix] 미리보기에서 차단된 유저의 댓글을 제외

keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/challenge/Challenge.java
현재 종료된 챌린지를 클릭하면 상세 정보에서 챌린지 참여가 가능한데요.
삭제된 챌린지를 참가처리하면, 정상 참여가 되는데 챌린지는 삭제 상태 그대로라 목록에 노출되지 않는 문제가 있어요
위 문제를 해소하는 PR이에요
=> [Fix] 챌린지 참가 시 챌린지의 deleted 상태를 변경해요

keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightCommentQueryApiService.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/CommentQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/CommentQueryDomainService.java
- close #298 
- 댓글의 첫 번째 답글이 차단된 유저의 것인 경우 다음 순서의 답글을 노출
- 댓글의 답글 수 조회 시 차단된 유저의 답글은 제외
- 쿼리에서 필터링을 적용해서 구현했어요
=> [Fix] 댓글 조회 API 쿼리에서 차단 필터링 적용

keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserProfileController.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/AccountResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserProfileControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/User.java
- close #306 
- 연결된 계정 조회 API 추가
=> [Feat] 설정 연결된 계정 API

keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/challenge/Challenge.java, keewe-domain/src/main/java/ccc/keewedomain/service/challenge/command/ChallengeCommandDomainService.java
=> [Fix] 챌린지 참가 버그 수정

keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java
=> [Fix] 챌린지 ApiService에 readOnly Tx 제거

keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/ProfileMyPageResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserProfileControllerTest.java
마이페이지에서 챌린지 상세로 이동할 수 있도록 ID를 내려줘요
=> [Fix] 마이페이지 응답에 참여중인 ChallengeId 추가

keewe-api/http/http-client.env.json, keewe-api/http/signup.http, keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserSignUpController.java, keewe-api/src/main/java/ccc/keeweapi/service/user/UserApiService.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/enums/VendorType.java, keewe-domain/src/main/java/ccc/keewedomain/service/user/UserDomainService.java, keewe-infra/src/main/java/ccc/keeweinfra/dto/VirtualProfileResponse.java
- 회원가입 타이틀 획득 버그를 수정해요.
- Tx Commit되는 시점에 유저 정보가 데이터베이스에 저장되기때문에, 타이틀 획득 이벤트를 발행하고 statistics 모듈에서 타이틀 획득처리할 때 유저 정보가 없을 수 있어요.
- Tx가 필요하지 않다고도 판단되어서, 제거하였고 JPA 쓰기 지연이 작동하지 않도록 수정했어요
=> [Fix] 최초 회원가입 타이틀 획득 버그 수정

keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java, keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserInvitationController.java, keewe-api/src/main/java/ccc/keeweapi/dto/user/InviteeSearchResponse.java, keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java, keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserInvitationControllerTest.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/FollowQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/cursor/InviteeSearchCursor.java, keewe-domain/src/main/java/ccc/keewedomain/service/user/query/ProfileQueryDomainService.java, keewe-domain/src/main/resources/ddl/ddl.sql
- close #333
- 초대 대상 (팔로잉/팔로워) 닉네임 검색 API를 개발했어요
=> [Feat] 팔로잉/팔로워 검색 API

keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java, keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java, keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
- 북마크 인사이트 시 아래 버그를 수정합니다.
1. 인사이트 데이터 순서 보장 -> List<Tuple>을 Map으로 변환하는과정에서 순서 보장 불가한 부분 수정
2. parallelStream 내에서 Jpa Entity Graph (연관관계 객체 탐색) 조회를 타게되면, 문제가 있네요.
-> 레디스 조회가 병렬 처리의 목적이므로 레디스 조회만 병렬처리로 별도 분리하고, Jpa stream 처리는 순차 처리로 수정합니다.
=> [Fix] 북마크 인사이트 목록 조회 버그 수정
